### ISSUE TITLE
Suggest to loosen the dependency on nameko

### ISSUE THREAD

**Issue by Agnes-U** [zsiciarz/nameko-structlog-experiment#1]
Hi, your project nameko-structlog-experiment(commit id: 64a8cacbbbbdc35eaca786ea6c3c432ac9cd7956) requires "nameko==2.14.1" in its dependency. After analyzing the source code, we found that the following versions of nameko can also be suitable, i.e., nameko 2.6.0, 2.7.0, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.9.0rc0, 2.9.0, 2.9.0-rc0, 2.9.1rc0, 2.9.1, 2.9.1-rc0, 2.10.0, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 3.0.0rc11, 3.0.0rc10, 3.0.0rc9, 3.0.0rc8, 3.0.0rc7, 3.0.0rc6, 3.0.0rc5, 3.0.0rc4, 3.0.0rc3, 3.0.0rc2, 3.0.0rc1, 3.0.0rc0, 3.0.0-rc11, 3.0.0-rc10, 3.0.0-rc9, 3.0.0-rc8, 3.0.0-rc7, 3.0.0-rc6, 3.0.0-rc5, 3.0.0-rc4, 3.0.0-rc3, 3.0.0-rc2, 3.0.0-rc1, 3.0.0-rc0, since all functions that you directly (2 APIs: nameko.extensions.Entrypoint.decorator, nameko.extensions.DependencyProvider.__init__) or indirectly (propagate to 0 nameko's internal APIs and 1 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on nameko from "nameko==2.14.1" to "nameko>=2.6.0,<=3.0.0-rc11". This will improve the applicability of nameko-structlog-experiment and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on nameko?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by zsiciarz** [comment]
Nope, that was a one-time experiment with no reason to maintain the dependencies anymore. Please, at least do your research before running an automated bot on Github.
